@startuml
skinparam linetype ortho
skinparam backgroundColor #1E1E1E
skinparam defaultTextAlignment center
skinparam ArrowColor #B0C4DE
skinparam shadowing false
skinparam FontColor #FFFFFF
skinparam classFontColor #FFFFFF
skinparam classAttributeFontColor #FFFFFF
skinparam classMethodFontColor #FFFFFF

skinparam class {
  BackgroundColor #2D2D2D
  BorderColor #8A8A8A
  FontColor #E0E0E0
}

!include Mapper.puml
!include ToEntityMapper.puml

interface CustomerRecipeRequestBodyToRecipeMapper extends Mapper, ToEntityMapper {
    + void map(CustomerRecipeRequestBody source, Recipe target)
    + Recipe mapToEntity(CustomerRecipeRequestBody customerRecipeRequestBody)
}

class DefaultCustomerRecipeRequestBodyToRecipeMapper implements CustomerRecipeRequestBodyToRecipeMapper {
    + Recipe mapToEntity(CustomerRecipeRequestBody requestBody)
    + void map(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapName(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapDescription(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapDifficulty(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapCategories(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapIngredients(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapServings(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapCookingTime(CustomerRecipeRequestBody requestBody, Recipe recipe)
    - void mapInstructions(CustomerRecipeRequestBody requestBody, Recipe recipe)
}
@enduml