openapi: 3.1.0
info:
  title: "Recipe API"
  description: "REST API for managing cooking recipes"
  version: 2.0.0

servers:
  - url: 'http://localhost:8080'

paths:
  /api/v2/recipes:
    post:
      security:
        - basicAuth: [ "adam" ]
      summary: "Create new recipe"
      requestBody:
        required: true
        description: "Recipe request body"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeRequestBody'
            example:
              name: "Toasts"
              description: "Easy recipe"
              difficulty: "EASY"
              categories: [ "Breakfast", "Fast" ]
              ingredients:
                - name: "Bread"
                  amount: 2
                  unit: "slices"
              servings: 2
              cookingTime: 5
              instructions: "Toast it."

      responses:
        '201':
          description: "Recipe created successfully"

    get:
      summary: "Get recipes list page"
      parameters:
        - name: pageNumber
          in: query
          required: true
          description: "Page number"
          schema:
            type: integer
            example: 0
        - name: pageSize
          in: query
          required: true
          description: "Number of recipes on the page"
          schema:
            type: integer
            example: 10

      responses:
        '200':
          description: "List of recipes on the page"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeResponseBody'
              example:
                - id: 1
                  name: "Toasts"
                  image: "BASE64_IMAGE_STRING"
                  description: "Easy recipe"
                  difficulty: "EASY"
                  categories: [ "Breakfast", "Fast" ]
                  ingredients:
                    - name: "Bread"
                      amount: 2
                      unit: "slices"
                  servings: 2
                  cookingTime: 5
                  instructions: "Toast it."
                - id: 2
                  name: "Pasta"
                  image: "BASE64_IMAGE_STRING"
                  description: "Simple pasta"
                  difficulty: "MEDIUM"
                  categories: [ "Dinner" ]
                  ingredients:
                    - name: "Pasta"
                      amount: 200
                      unit: "grams"
                  servings: 2
                  cookingTime: 12
                  instructions: "Boil pasta."

  /api/v2/recipes/{id}:
    get:
      summary: "Get recipe by id"
      parameters:
        - name: id
          in: path
          required: true
          description: "Recipe id"
          schema:
            type: integer
            example: 1

      responses:
        '200':
          description: "Recipe found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeResponseBody'
              example:
                id: 1
                name: "Toasts"
                image: "BASE64_IMAGE_STRING"
                description: "Easy recipe"
                difficulty: "EASY"
                categories: [ "Breakfast", "Fast" ]
                ingredients:
                  - name: "Bread"
                    amount: 2
                    unit: "slices"
                servings: 2
                cookingTime: 5
                instructions: "Toast it."

    put:
      summary: "Update recipe by ID"
      parameters:
        - name: id
          in: path
          required: true
          description: "Recipe id"
          schema:
            type: integer
            example: 1

      requestBody:
        required: true
        description: "Recipe request body"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeRequestBody'
            example:
              name: "Medium Toasts"
              description: "Medium recipe"
              difficulty: "MEDIUM"
              categories: [ "Breakfast", "Fast" ]
              ingredients:
                - name: "Bread"
                  amount: 2
                  unit: "slices"
              servings: 2
              cookingTime: 5
              instructions: "Toast it."

      responses:
        '200':
          description: "Recipe updated successfully"

    delete:
      summary: "Delete recipe by ID"
      parameters:
        - name: id
          in: path
          required: true
          description: "Recipe id"
          schema:
            type: integer
            example: 1

      responses:
        '200':
          description: "Recipe deleted successfully"

  /api/v2/recipes/search:
    get:
      summary: "Find recipe by name/description"
      parameters:
        - name: text
          in: query
          required: true
          description: "Recipe name/description"
          schema:
            type: string
            example: "Toast"
        - name: pageNumber
          in: query
          required: true
          description: "Page number"
          schema:
            type: integer
            example: 0
        - name: pageSize
          in: query
          required: true
          description: "Number of recipes on the page"
          schema:
            type: integer
            example: 10

      responses:
        '200':
          description: "List of recipes on the page"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeResponseBody'
              example:
                - id: 1
                  name: "Toasts"
                  image: "BASE64_IMAGE_STRING"
                  description: "Easy recipe"
                  difficulty: "EASY"
                  categories: [ "Breakfast", "Fast" ]
                  ingredients:
                    - name: "Bread"
                      amount: 2
                      unit: "slices"
                  servings: 2
                  cookingTime: 5
                  instructions: "Toast it."
                - id: 2
                  name: "Pasta"
                  image: "BASE64_IMAGE_STRING"
                  description: "Simple pasta"
                  difficulty: "MEDIUM"
                  categories: [ "Dinner" ]
                  ingredients:
                    - name: "Pasta"
                      amount: 200
                      unit: "grams"
                  servings: 2
                  cookingTime: 12
                  instructions: "Boil pasta."

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: "Use Basic Auth. Username: <user>, Password: <user>"

  schemas:
    RecipeRequestBody:
      type: object
      required: [
        name,
        description,
        difficulty,
        categories,
        ingredients,
        servings,
        cookingTime,
        instructions
      ]
      properties:
        name:
          type: string
          minLength: 1
        image:
          type: string
          format: binary
        description:
          type: string
          minLength: 1
        difficulty:
          type: string
          enum: [ EASY, MEDIUM, HARD ]
        categories:
          type: array
          minItems: 1
          items:
            type: string
            minLength: 1
        ingredients:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/IngredientRequestBody'
        servings:
          type: number
          format: double
          minimum: 1.0
        cookingTime:
          type: integer
          minimum: 0
        instructions:
          type: string
          minLength: 1

    IngredientRequestBody:
      type: object
      required: [
        name,
        amount,
        unit
      ]
      properties:
        name:
          type: string
          minLength: 1
        amount:
          type: number
          format: double
          minimum: 0.1
        unit:
          type: string
          minLength: 1

    RecipeResponseBody:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
          format: binary
        description:
          type: string
        difficulty:
          type: string
          enum: [ EASY, MEDIUM, HARD ]
        categories:
          type: array
          items:
            type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/IngredientResponseBody'
        servings:
          type: number
          format: double
        cookingTime:
          type: integer
        instructions:
          type: string

    IngredientResponseBody:
      type: object
      properties:
        name:
          type: string
        amount:
          type: number
          format: double
        unit:
          type: string

security:
  - basicAuth: [ ]