@startuml
title Delete Recipe - Sequence

autonumber

skinparam sequence {
  MessageAlign center
}
skinparam NoteBackgroundColor #1C2330
skinparam NoteBorderColor #E7E7E7
skinparam NoteFontColor #F5F5F5
skinparam ActorStyle awesome

actor Client
boundary Application
control RecipeRestControllerV1
control RecipeServiceV1
database database
control GlobalExceptionHandler

Client -> Application : DELETE /api/v1/recipes/{id}
Application -> RecipeRestControllerV1 : delegate request
RecipeRestControllerV1 -> RecipeServiceV1 : delegate request
note right of RecipeServiceV1
check id existence
end note

alt id exists
    database -> RecipeServiceV1 : recipe
    RecipeServiceV1 -> database : delete recipe
    RecipeServiceV1 -> RecipeRestControllerV1 : deleted recipe
    RecipeRestControllerV1 -> Application : RecipeDTO
    Application -> Client : OK (200) + RecipeDTO
else id doesn't exist
    RecipeServiceV1 -> GlobalExceptionHandler : exception
    GlobalExceptionHandler -> RecipeRestControllerV1 : ErrorHttpResponse
    RecipeRestControllerV1 -> Application : ErrorHttpResponse
    Application -> Client : Not Found (404) + ErrorHttpResponse
end
@enduml