@startuml
title Get recipe by id - Sequence

autonumber

skinparam backgroundColor #0E1117
skinparam shadowing false
skinparam roundcorner 12
skinparam dpi 160

skinparam sequence {
  MessageAlign center
  ArrowColor #58A6FF
  LifeLineBorderColor #30363D
  LifeLineBackgroundColor #161B22
  ActorBorderColor #58A6FF
  ActorBackgroundColor #0D1117
  BoxBorderColor #30363D
  BoxBackgroundColor #0D1117
}

skinparam TitleFontColor #C9D1D9
skinparam SequenceGroupBorderColor #30363D
skinparam SequenceGroupBackgroundColor #161B22
skinparam NoteBackgroundColor #1C2330
skinparam NoteBorderColor #E7E7E7
skinparam NoteFontColor #F5F5F5
skinparam ActorStyle awesome
skinparam DefaultFontColor #C9D1D9

skinparam BoundaryBorderColor #58A6FF
skinparam BoundaryBackgroundColor #0D1117

skinparam ControlBorderColor #58A6FF
skinparam ControlBackgroundColor #0D1117

skinparam DatabaseBorderColor #58A6FF
skinparam DatabaseBackgroundColor #0D1117

skinparam ParticipantBorderColor #58A6FF
skinparam ParticipantBackgroundColor #0D1117

actor User
boundary Application
control RecipeRestControllerV2
control RecipeServiceV2
database RecipesDatabase
control RecipeRestControllerV2LoggingAspect
control GlobalExceptionsHandler

User -> Application : GET /api/v2/recipes/{id}
Application -> RecipeRestControllerV2 : delegate request
note right of RecipeRestControllerV2LoggingAspect : log entry
RecipeRestControllerV2 -> RecipeServiceV2 : delegate request
note right of RecipeServiceV2 : validates id

alt id exists
    RecipeServiceV2 -> RecipesDatabase : get recipe by id
    RecipesDatabase -> RecipeServiceV2 : recipe
    RecipeServiceV2 -> RecipeRestControllerV2 : recipe
    RecipeRestControllerV2 -> Application : Http ok (200) + RecipeResponseBody
    note right of RecipeRestControllerV2LoggingAspect : log response
    Application -> User : Http ok (200) + RecipeResponseBody
else id doesn't exist
    RecipeRestControllerV2 -> RecipeRestControllerV2LoggingAspect : throw exception
    note right of RecipeRestControllerV2LoggingAspect : log error
    RecipeRestControllerV2LoggingAspect -> GlobalExceptionsHandler : re-throw exception
    note right of GlobalExceptionsHandler : log error
    RecipeRestControllerV2 -> Application : Http not found (404)
    Application -> User : Http not found (404)
end
@enduml